ARG version
FROM almalinux:${version:-10}
ARG sudheer=goodboy
ARG pranavi=badgirl
ENV pranavi=${pranavi}
RUN echo "sudheer = ${sudheer} pranavi = ${pranavi} "
CMD ["sleep", "200"]

# How you check your OS version of your sever? cat /etc/*release